<a href="https://colab.research.google.com/github/Adela-Jones/DS1_Homework_1_loading/blob/main/DS1_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import json

In [2]:
df1='/content/Data/Home_Infusion_Therapy_Providers_Sep_21_2026.csv'
read_df1=pd.read_csv(df1)
read_df1.head(11)

,Enrollment ID,Legal Business Name,Street Address Line 1,Street Address Line 2,City,State,ZIP Code,Practice Location Phone Number,Specialty Name,Geographic Location Type Description,Geographic Location City Name,Geographic Location State Code,Geographic Location ZIP Code,State County Name
0,O20201116001628,CRESCENT HEALTHCARE INC,5431 SW 35TH DR,STE 200,GAINESVILLE,FL,32608-5277,(844) 373-8389,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
1,O20250730000500,"KABAFUSION CO, LLC",12450 E ARAPAHOE RD,--,CENTENNIAL,CO,80112-3971,(877) 369-7213,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CO,--,--
2,O20210121000184,I V SOLUTIONS LLC,165 HANSEN CT,STE 106,WOOD DALE,IL,60191-1110,8479454444-1110,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,IL,--,LAKE
3,O20231019000440,PERPETUAL MOBILE MED,5015 EAGLE ROCK BLVD,STE 200,LOS ANGELES,CA,90041-2087,(323) 455-4868,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CA,--,--
4,O20220203001062,MKARE MANAGEMENT INC,147 AUBURN RDG,--,SPRING BRANCH,TX,78070-6001,(210) 663-1886,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,TX,--,GUADALUPE
5,O20250428002383,INFUPHARMA LLC,1239 NE 8TH AVE,--,FORT LAUDERDALE,FL,33304-2001,(954) 923-3839,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
6,O20260127003422,KABAFUSION TN LLC,2970 SIDCO DR,--,NASHVILLE,TN,37204-3715,(877) 397-8341,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,GA,--,--
7,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CA,--,SAN DIEGO
8,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,SUPPLIER GR. AREA,--,CA,--,ORANGE
9,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,SUPPLIER GR. AREA,--,CA,--,TULARE
10,O20260325003657,AGIOS CORP,1314 S BAY ST,--,EUSTIS,FL,32726-5551,(325) 357-6699,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--

**DF1 represents the following:**
Information on the providers in Medicare who specialize in Home Infusion Therapy

**Columns:**

**1. Enrollment ID**

* Represents the enrollment ID of the provider

**2. Legal Business Name**

* Represents the legal business name of the organization

**3. Street Address Line 1**

* Represents the 1st line of the street address

**4. Street Address Line 2**

* Represents the 2nd line of the street address

**5. City**

* Represents the City the organization is located

**6. State**

* Represents the state the organization is located

**7. ZIP Code**

* Represents the ZIP Code of the organization

**8. Practice Location Phone Number**

* Represents the phone number of the practice location

**9. Specialty Name**

* Represents the providers specialty

**10. Geographic Location Type Description**

* Represents the geographic location of the organization

**11. Geographic Location City Name**

* Represents the City of the organziations geographic location

**12. Geographic Location State Code**

* Represents the state code of the geographic location the organization is in

**13. Geographic Location ZIP Code**

* Represents the ZIP Code of the geographic location the organization is in

**14. State County Name**

* Represents the State County name in which the practice is located

In [9]:
df2='/content/Data/Medicare_Telehealth_Trends_Q1_2026.csv'
read_df2=pd.read_csv(df2)
read_df2.head(11)

,Year,Quarter,Bene_Geo_Desc,Bene_Mdcd_Mdcr_Enrl_Stus,Bene_Race_Desc,Bene_Sex_Desc,Bene_Mdcr_Entlmt_Stus,Bene_Age_Desc,Bene_RUCA_Desc,Total_Bene_TH_Elig,Total_PartB_Enrl,Total_Bene_Telehealth,Pct_Telehealth
0,2020,Overall,National,All,All,All,All,All,All,"30,946,785","32,244,894","14,826,919",47.9%
1,2020,Overall,National,All,All,All,All,All,Rural,"7,182,616","7,493,527","2,859,483",39.8%
2,2020,Overall,National,All,All,All,All,All,Urban,"23,699,049","24,631,424","11,945,312",50.4%
3,2020,Overall,National,All,All,All,All,All,Unknown,NaN,NaN,NaN,NaN
4,2020,Overall,National,All,All,All,All,0-64,All,"4,088,345","4,291,403","2,322,324",56.8%
5,2020,Overall,National,All,All,All,All,65-74,All,"14,440,791","15,326,715","6,495,728",45.0%
6,2020,Overall,National,All,All,All,All,75-84,All,"8,507,543","8,770,470","4,133,907",48.6%
7,2020,Overall,National,All,All,All,All,85 and over,All,"3,910,106","3,856,306","1,874,960",48.0%
8,2020,Overall,National,All,All,All,Aged,All,All,"26,643,001","27,762,319","12,371,786",46.4%
9,2020,Overall,National,All,All,All,Disabled,All,All,"3,869,764","4,092,286","2,192,809",56.7%
10,2020,Overall,National,All,All,All,ESRD,All,All,"434,020","390,288","262,324",60.4%

**DF2 represents the following:**

Information regarding Telehealth Trends extracted in Q1 2026

**Columns:**

**1. Year**

* Identifies the year from which the data was extracted

**2. Quarter**

* Represents the data quarter from when the data was pulled

**3. Beneficiary Geographic Description**

* Provides the geographic area of the beneficiary

**4. Beneficiary Medicaid Medicare Enrollment Status**

* Indicates whether the beneficiary is dually eligible for both programs

**5. Beneficiary Race Description**

* Describes a beneficiary's racial or ethnic identity

**6. Beneficiary Sex Description**

* Describes the biological sex of the beneficiary

**7. Beneficiary Medicare Entitlement Status**

* Defines whether the beneficiary is qualified, enrolled and active to receive benefits under the Medicare program

**8. Beneficiary Age Description**

* Provides a breakdown of the beneficaries ages

**9. Beneficiary RUCA Description**

* Lists whether the beneficiary lives in an urban or rural commuting area

**10. Total Beneficiary TeleHealth Eligibility**

* Represents the complete count of Medicare beneficiaries who are eligible to receive Telehealth services

**11. Total Part B Enrollment**

* Represents the total amount of beneficiaries enrolled in Part B

**12. Total Beneficiary Telehealth**

* Represents the number of unique Medicare beneficiaries with Telehealth

**13. Percent Telehealth**

* Represents the percentage of unique Medicare beneficiaries who used a telehealth service

In [10]:
df3='/content/Data/Medicare_Provider_and_Supplier_Taxonomy_Crosswalk_Aug_24_2026.csv'
read_df3=pd.read_csv(df3)
read_df3.head(11)

,MEDICARE SPECIALTY CODE,MEDICARE PROVIDER/SUPPLIER TYPE DESCRIPTION,PROVIDER TAXONOMY CODE,"PROVIDER TAXONOMY DESCRIPTION: TYPE, CLASSIFICATION, SPECIALIZATION"
0,01,Physician/General Practice,208D00000X,Allopathic & Osteopathic Physicians/General Pr...
1,02,Physician/General Surgery,208600000X,Allopathic & Osteopathic Physicians/Surgery
2,02,Physician/General Surgery,2086H0002X,Allopathic & Osteopathic Physicians/Surgery/Ho...
3,02,Physician/General Surgery,2086S0120X,Allopathic & Osteopathic Physicians/Surgery/Pe...
4,02,Physician/General Surgery,2086S0122X,Allopathic & Osteopathic Physicians/Surgery/Pl...
5,02,Physician/General Surgery,2086S0105X,Allopathic & Osteopathic Physicians/Surgery/Su...
6,02,Physician/General Surgery,2086S0102X,Allopathic & Osteopathic Physicians/Surgery/Su...
7,02,Physician/General Surgery,2086X0206X,Allopathic & Osteopathic Physicians/Surgery/Su...
8,02,Physician/General Surgery,2086S0127X,Allopathic & Osteopathic Physicians/Surgery/Tr...
9,02,Physician/General Surgery,2086S0129X,Allopathic & Osteopathic Physicians/Surgery/Va...
10,02,Physician/General Surgery,208G00000X,Allopathic & Osteopathic Physicians/Thoracic S...

**DF3 represents the following:**

Information about Medicare provider/supplier Taxonomy extracted August 2026

**Columns:**

**1. Medicare Specialty Code**

* Specialty code that corresponds to the listed Medicare specialty

**2. Medicare Provider/Supplier Type Description**

* The description of the Medicare provider/supplier type

**3. Provider Taxonomy Description**

* The taxonomy code the providers use

**4. Provider Taxonomy Description: Type, Classification, Specialization**

* The description of the taxonomy that the providers use

In [11]:
jsonf1 = '/content/Data/Air Quality & Health Impacts State of NY.json'
read_jsonf1=pd.read_json(jsonf1)
read_jsonf1.head(11)

,:id,:version,:created_at,:updated_at,unique_id,indicator_id,name,measure,measure_info,geo_type_name,geo_join_id,geo_place_name,time_period,start_date,data_value
0,row-rxsa~rtkc-tzkh,rv-dk3z~evyw.3uc4,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,979194,1427,Fine particles (PM 2.5),Winter mean,mcg/m3,UHF34,104,Pelham - Throgs Neck,2024,2024-01-01T00:00:00.000,5.834572
1,row-ka9w~3p8v~ncvs,rv-5w28~zup2-zikn,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980097,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,304,Upper West Side,2024,2024-01-01T00:00:00.000,18.288730
2,row-vh92_d3s6-y8cr,rv-v4g7-5ycv.953x,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980098,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,303,East Harlem,2024,2024-01-01T00:00:00.000,16.184849
3,row-pzcp-gck3_kizz,rv-6evi_aafz.tvbg,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980099,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,302,Central Harlem - Morningside Heights,2024,2024-01-01T00:00:00.000,16.521823
4,row-fm7t.gw9j-vjtm,rv-zz95~hzn5-kac4,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980100,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,301,Washington Heights,2024,2024-01-01T00:00:00.000,16.264552
5,row-2g7u~p3zf.jrvz,rv-84jd_8hge~8hbq,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980101,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,211,Williamsburg - Bushwick,2024,2024-01-01T00:00:00.000,15.822502
6,row-jdj3-uk6h_nrhx,rv-3nyt-y2sm~uu4v,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980102,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,210,Coney Island - Sheepshead Bay,2024,2024-01-01T00:00:00.000,12.242542
7,row-a5cs_cywv-zvsz,rv-ke7q_eqhx~pbyf,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980103,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,209,Bensonhurst - Bay Ridge,2024,2024-01-01T00:00:00.000,14.075246
8,row-xjff-jhs3.sv3b,rv-t9wn.nq82-p8bf,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980104,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,208,Canarsie - Flatlands,2024,2024-01-01T00:00:00.000,12.394516
9,row-fkzc_vcjh.rv9e,rv-vjsn.gzwx_crdv,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980105,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,207,East Flatbush - Flatbush,2024,2024-01-01T00:00:00.000,14.387884
10,row-psbu.yvdc~44ym,rv-yryh_y2qt-tibw,2026-06-18 18:46:06.561000+00:00,2026-06-18 18:46:06.561000+00:00,980106,1431,Nitrogen dioxide (NO2),Annual mean,ppb,UHF34,206,Borough Park,2024,2024-01-01T00:00:00.000,14.453190

**JSONF1 represents the following:**

Information on New York City air quality surveillance updated as of June 2026

**Columns:**

**1. Unique ID**

* Represents the unique record identifier

**2. Indicator ID**

* Identifies the type of measure value across time and space

 **3. Name**

* Represents the name of the indicator

**4. Measure**

* Represents how the Indicator is measured

 **5. Measure Information**

* Information such as units about the measure

**6. Geography Type Name**

* Represents the geography type example; Borough, Citywide

 **7. Geographic Join ID**

* Identifier for neighberhood geographic areas for joining to mapping geography files to make thematic maps

**8. Geography Place Name**

* Represents the neighborhood name

**9. Time Period**

* Description of the time the data applies to

**10. Start Date**

* Date value for the start of the time period

**11. Data Value**

* The data value for the indicator, measure, place and time

In [13]:
jsonf2='/content/Data/Leading Causes of Death US.json'
read_jsonf2=pd.read_json(jsonf2)
read_jsonf2.head(11)

,:id,:version,:created_at,:updated_at,year,_113_cause_name,cause_name,state,deaths,aadr
0,row-s9c2_shuj.u3r7,rv-cj99_8n3p.zhnz,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2012,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,21,2.6
1,row-xdyq~3cey~j2k3,rv-vyyg-uv8g.yukq,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2017,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,29,3.3
2,row-nwn9-fqhw_h3ca,rv-yw74~mjju_uct9,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2016,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,30,3.7
3,row-xv2h_xkub-jcyw,rv-tpsi_pahh~cajz,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2013,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,30,3.8
4,row-3kd4~edcb.rsvd,rv-bfrt~542p_dtk9,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2000,"Intentional self-harm (suicide) (*U03,X60-X84,...",Suicide,District of Columbia,23,3.8
5,row-xjwv.gc2r.3hdi,rv-eatw_ru2q_82pq,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2014,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Arizona,325,4.1
6,row-g7y2.wym8_hcu2,rv-9c9z-wmyf-e5eg,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2009,"Intentional self-harm (suicide) (*U03,X60-X84,...",Suicide,District of Columbia,29,4.4
7,row-tts4_akwe-amn7,rv-kjuh_2yhg-26g6,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2015,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,39,4.5
8,row-qgw8-m7pt-dtst,rv-q9vx~6wf9_ezdt,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2014,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,Vermont,37,4.5
9,row-yu4c~bw4t.vz24,rv-kz9b_kqs3.9nyt,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2011,"Nephritis, nephrotic syndrome and nephrosis (N...",Kidney disease,South Dakota,49,4.5
10,row-j9w8_ubfz_f5y3,rv-ya9q_ai9j~iuzf,2019-10-24 14:19:44.587000+00:00,2019-10-24 14:19:44.587000+00:00,2015,"Intentional self-harm (suicide) (*U03,X60-X84,...",Suicide,District of Columbia,34,4.9

**JSONF2 Represents the following:**

Age adjusted death rates for the 10 leading causes of death in the United States beginning in 1999

**Columns:**

**1. Year**

* Represents the year the death occurred

**2. 113 Cause Name**

* Represents a specific standardized subcategories of death as created by the National Center for Health Statistics

**3. Cause Name**

* Represents the simplified category name for the leading causes of death such as Heart Disease, Cancer or Stroke

**4. State**

* The geographic location where the death occurred

**5. Deaths**

* Represents the total number of individuals who died from that specific cause

**6. Age Adjusted Death Rate**

* Represents the number of deaths per 100,000 people

In [14]:
jsonf3='/content/Data/Lottery Mega Millions Winning Numbers.json'
read_jsonf3=pd.read_json(jsonf3)
read_jsonf3.head(11)

,:id,:version,:created_at,:updated_at,draw_date,winning_numbers,mega_ball,multiplier
0,row-2zvw.8wby-6cep,rv-mt2j~ifde_qeuc,2026-09-23 07:33:07.315000+00:00,2026-09-23 07:33:07.315000+00:00,2026-09-22T00:00:00.000,07 13 26 37 68,8,NaN
1,row-j77p.ica4-izwc,rv-tfvb~ctw4_gzpp,2026-09-19 07:33:06.054000+00:00,2026-09-19 07:33:06.054000+00:00,2026-09-18T00:00:00.000,04 09 24 56 68,1,NaN
2,row-9pzr~94di-vevh,rv-sgt2-2dvi-ekew,2026-09-16 12:13:50.450000+00:00,2026-09-16 12:13:50.450000+00:00,2026-09-15T00:00:00.000,27 36 43 57 58,16,NaN
3,row-5zd2-mht4~d3jr,rv-r73e~wusa-79n9,2026-09-12 07:33:10.707000+00:00,2026-09-12 07:33:10.707000+00:00,2026-09-11T00:00:00.000,03 30 33 53 62,22,NaN
4,row-nevm-2g3h~4dbj,rv-g2d3.vvjx_puti,2026-09-09 07:33:12.882000+00:00,2026-09-09 07:33:12.882000+00:00,2026-09-08T00:00:00.000,17 30 43 58 66,20,NaN
5,row-ehe5_z79c.4xz2,rv-mxc3.dfhs-yp75,2026-09-05 07:33:20.350000+00:00,2026-09-05 07:33:20.350000+00:00,2026-09-04T00:00:00.000,06 26 34 59 61,24,NaN
6,row-eks8-sfs4_x4vc,rv-89w7_496a-ajmv,2026-09-02 07:33:00.409000+00:00,2026-09-02 07:33:00.409000+00:00,2026-09-01T00:00:00.000,01 22 51 61 63,17,NaN
7,row-taca~tvhe_5jru,rv-nf9k_2bc8-u75s,2026-08-29 07:32:59.950000+00:00,2026-08-29 07:32:59.950000+00:00,2026-08-28T00:00:00.000,08 17 29 42 55,2,NaN
8,row-7ct3~jj86-xnt3,rv-ttgf_47td_v5xv,2026-08-26 07:33:31.658000+00:00,2026-08-26 07:33:31.658000+00:00,2026-08-25T00:00:00.000,07 10 47 48 50,14,NaN
9,row-y8rt_knix.hnix,rv-7x4g_wz38-f8gc,2026-08-22 07:32:56.423000+00:00,2026-08-22 07:32:56.423000+00:00,2026-08-21T00:00:00.000,01 25 34 48 57,24,NaN
10,row-swtx~np9f~qmyh,rv-xdxb~f73v-u6ve,2026-08-19 20:59:08.994000+00:00,2026-08-19 20:59:08.994000+00:00,2026-08-18T00:00:00.000,05 19 30 38 59,12,NaN

**JSONF3 represents the following:**

NY State Lottery Mega Millions Winning Numbers beginning in 2002

**Columns:**

**1. Draw Date**

* The exact date the drawing took place

**2. Winning Numbers**

* Represents the numbers that were drawn

**3. Mega Ball**

* Represents the number that was drawn as the Mega Ball

**4. Multiplier**

*  Represents the multiplier that will be randomly assigned to the drawing. It could be a value of 2x, 3x or 4x

In [21]:
excelf1='/content/Data/Motor_Vehicle_Occupant_Death_Rate,_by_Age_and_Sex,_2012_&_2014,_All_States_20260923.xlsx'
read_excelf1=pd.read_excel(excelf1)
read_excelf1.head(11)

,State,Location,"All Ages, 2012","All Ages, 2014","Age 0-20, 2012","Age 0-20, 2014","Age 21-34, 2012","Age 21-34, 2014","Age 35-54, 2012","Age 35-54, 2014","Age 55+, 2012","Age 55+, 2014","Male, 2012","Male, 2014","Female, 2012","Female, 2014"
0,Alabama,"Alabama (32.839182, -86.631125)",13.7,13.0,8.6,6.9,20.8,17.8,12.6,14.2,15.5,14.6,17.6,17.2,10.0,9.0
1,Alaska,"Alaska (64.836661, -147.738891)",5.4,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.5,7.5,NaN,NaN
2,Arizona,"Arizona (34.869712, -111.760902)",7.4,6.0,5.0,3.4,12.0,8.4,7.3,6.0,6.9,6.9,10.2,7.3,4.7,4.8
3,Arkansas,"Arkansas (34.748745, -92.275105)",13.8,12.0,8.0,6.2,20.3,15.1,13.8,13.6,16.2,14.0,17.3,16.0,10.4,8.1
4,California,"California (37.640735, -121.002435)",4.2,4.3,2.4,2.7,6.9,6.9,4.0,3.5,4.5,4.7,5.6,5.7,2.7,2.8
5,Colorado,"Colorado (38.841772, -106.132562)",5.8,6.0,3.3,3.6,8.8,8.7,4.8,5.5,7.3,6.7,7.4,7.5,4.1,4.4
6,Connecticut,"Connecticut (41.544654, -72.651713)",4.1,4.0,NaN,NaN,7.5,7.9,4.0,4.0,5.2,3.5,5.4,6.0,2.9,2.0
7,Delaware,"Delaware (39.008676, -75.574561)",6.9,8.2,NaN,NaN,13.0,16.6,NaN,NaN,NaN,9.7,10.0,10.3,4.1,6.3
8,District of Columbia,"District of Columbia (38.892062, -77.019912)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Florida,"Florida (28.915325, -81.922409)",6.4,6.1,3.5,3.1,10.0,9.5,6.7,6.0,7.2,6.7,8.4,8.0,4.4,4.2
10,Georgia,"Georgia (32.836038, -83.631709)",8.5,8.3,3.9,3.7,12.1,11.1,8.2,8.5,12.1,10.6,11.7,11.3,5.5,5.5

**Excel F1 represents the following:**

Rate and deaths by age/sex per 100,000 population for motor vehicle occcupants killed in crashes from 2012 & 2014

**Columns:**

**1. State**

* State where the death occurred.

**2. Location**

* Location of where the death occurred

**3. All Ages 2012**

* Represents the total number of motor vehicle occupants of any age killed in a traffic crash during 2012

**4. All Ages 2014**

* Represents the total number of motor vehicle occupants of any age killed in a traffic crash during 2014

**5. Age 0-20, 2012**

* Total number of occupants ages 0-20 killed in a traffic crash during 2012

**6. Age 0-20, 2014**

* Total number of occupants ages 0-20 killed in a traffic crash during 2014

**7. Age 21-34, 2012**

* Total number of occupants ages 21-34 killed in a traffic crash during 2012

**8. Age 21-34, 2014**

* Total number of occupants ages 21-34 killed in a traffic crash during 2014

**9. Age 35-54, 2012**

* Total number of occupants ages 35-54 killed in a traffic crash during 2012

**10. Age 35-54, 2014**

* Total number of occupants ages 35-54 killed in a traffic crash during 2014

**11. Age 55+, 2012**

* Total number of occupants ages 55+ killed in a traffic crash during 2012

**12. Age 55+, 2014**

* Total number of occupants ages 55+ killed in a traffic crash during 2014

**13. Male, 2012**

* Total number of male occupants killed in a traffic crash in 2012

**14. Male, 2014**

* Total number of male occupants killed in a traffic crash in 2014

**15. Female, 2012**

* Total number of female occupants killed in a traffic crash in 2012

**16. Female, 2014**

* Total number of female occupants killed in a traffic crash in 2014

In [24]:
excelf2='/content/Data/School-Fine- Reports 2010.xlsx'
read_excelf2=pd.read_excel(excelf2)
read_excelf2.head(11)

,Fines Imposed by Federal Student Aid in Fiscal Year 2010,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,OPEID,School,City,State,School Type,Referral Reason,Imposed Fine\nAmount,Imposed Fine \nDate
1,02280500,Charles of Italy Beauty College,Lake Havasu City,AZ,Prop,IPEDS Nonsubmission,15750,2009-10-26 00:00:00
2,03445300,HDS Truck Driving Institute,Tucson,AZ,Prop,IPEDS Nonsubmission,1000,2009-10-15 00:00:00
3,02098800,University of Phoenix,Tempe,AZ,Prop,Qui Tam,48500000,2009-12-15 00:00:00
4,03698400,California College of Vocational Careers,Bakersfield,CA,Prop,IPEDS Nonsubmission,3500,2009-10-27 00:00:00
5,02125000,Career Academy of Beauty,Garden Grove,CA,Prop,IPEDS Nonsubmission,7000,2009-10-26 00:00:00
6,03162300,Four-D College,Colton,CA,Prop,IPEDS Nonsubmission,5000,2009-10-08 00:00:00
7,00565500,Hacienda La Puente Adult Education,La Puente,CA,Pub,IPEDS Nonsubmission,8750,2009-10-08 00:00:00
8,02228500,Life Chiropractic College West,Hayward,CA,Priv,IPEDS Nonsubmission,15000,2009-10-28 00:00:00
9,01047400,Marymount California University,Rancho Palos Verdes,CA,Priv,IPEDS Nonsubmission,7500,2009-10-26 00:00:00
10,03590400,NTMA Training Centers of Southern California,Santa Fe Springs,CA,Priv,IPEDS Nonsubmission,17500,2009-10-08 00:00:00

**Excel F2 represents the following:**

Information regarding eligibility and compliance reports about the approximately 6,000 post secondary institutions that participate in the Title IV programs and fines imposed for the year 2010

**Columns:**

**1. OPEID**

* Represents the unique 8 digit identification code assigned by the U.S Dept. of education to colleges, universities and technical schools

**2. School**

* The name of the School

**3. City**

*City where the school is physically located

**4. State**

* State where the school is located

**5. School Type**

* Represents if the school is private, public or proprietary


**6. Referral Reason**

* The reason why the school was flagged

**7. Imposed Fine Amount**

* The exact dollar amount penalty the school is ordered to pay

**8. Imposed Fine Date**

* The offical date the imposed fine was finalized and issued to the school

In [25]:
excelf3='/content/Data/2026-9-18-iolp-buildings.xlsx'
read_excelf3=pd.read_excel(excelf3)
read_excelf3.head(11)

,Location Code,Real Property Asset Name,Installation Name,Owned or Leased,GSA Region,Street Address,City,State,Zip Code,Latitude,Longitude,Building Rentable Square Feet,Available Square Feet,Construction Date,Congressional District,Congressional District Representative Name,Building Status,Real Property Asset Type
0,AK0001,ANCHORAGE HISTORIC FEDERAL BUILDING,ANCHORAGE FEDERAL,OWNED,10,605 W 4TH AVE,ANCHORAGE,AK,99501.0,61.218871,-149.89446,91737.92,30404.6778,4610.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
1,AK0005,KETCHIKAN FEDERAL BUILDING,KETCHIKAN FEDERAL,OWNED,10,648 MISSION ST,KETCHIKAN,AK,99901.0,55.341585,-131.64269,33745.89,11503.8217,3881.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
2,AK0009,POST OFFICE AND CU H,NaN,LEASED,10,2ND ST 112 FEDERAL WAY,WRANGELL,AK,99929.0,56.473949,-132.38812,97.00,NaN,NaN,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
3,AK0013,HURFF A. SAUNDERS FB & ROBERT BOOCHEVER USCH,NaN,OWNED,10,709 W 9TH ST FB/USPO/USCH,JUNEAU,AK,99801.0,58.301356,-134.42035,283671.02,12182.1300,4108.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
4,AK0029,FAIRBANKS FEDERAL BUILDING,NaN,OWNED,10,101 12TH AVE,FAIRBANKS,AK,99701.0,64.837910,-147.70677,99583.50,10321.1706,8126.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
5,AK0031,ANCHORAGE FED. BLDG & JAMES M. FITZGERALD USCH,FED BLDG-USCH,OWNED,10,222 W 7TH AVE,ANCHORAGE,AK,99501.0,61.215102,-149.88520,455604.47,5160.7078,7760.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
6,AK0032,ANCHORAGE FEDERAL BUILDING US COURTHOUSE ANNEX,FED BLDG-USCH,OWNED,10,222 W 8TH AVE,ANCHORAGE,AK,99513.0,61.214328,-149.88632,64821.42,8291.3292,9221.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
7,AK0036,ALCAN RECREATION BUILDING,ALCAN LPOE,OWNED,10,MILEPOST 1221.8 ALASKA HWY,TOK,AK,99780.0,62.621860,-141.00959,1449.80,0.0000,5934.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
8,AK0037,ALCAN POLE BUILDING,ALCAN LPOE,OWNED,10,MILEPOST 1221.8 ALASKA HWY,TOK,AK,99780.0,62.621910,-141.00976,1026.06,0.0000,5934.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
9,AK0038,POKER CREEK LAND PORT OF ENTRY,NaN,OWNED,10,TAYLOR HIGHWAY,TOK,AK,99780.0,64.085639,-141.00153,1457.19,0.0000,6770.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING
10,AK0040,ALCAN LAND LEASE,ALCAN LPOE,OWNED,10,MILEPOST 1221.8 ALASKA HWY,TOK,AK,99780.0,62.621671,-141.01025,3500.00,0.0000,6299.0,200.0,NICHOLAS J. BEGICH III,ACTIVE,BUILDING

**Excel F3 represents the following information:**

Inventory of owned and Leased properties leased by the General Services Administration across the United States, Puerto Rico, Guam, and American Samoa.

**Columns:**

**1. Location Code**

* Represents the unique code to identify the sepcific building or property

**2. Real Property Asset Name**

* The common name or title of the building

**3. Installation Name**

* Identifies whether the property belongs to a larger installation

**4. Owned or Leased**

* Indicates whether the federal government owns or rents the property

**5. GSA Region**

* The geographic region assigned by the GSA

**6. Street Region**

* The street address of the property

**7. City**

* The City where the property is located

**8. Zip Code**

* The postal ZIP Code of  the property

**9. Latitude**

* Represents the geographic GPS coordinates used for mapping the building

**10. Longitude**

* Represents the geographic GPS coordinates used for mapping the building

**12. Building Rentable Square Feet**

* The total rentable square footage available inside the building structure

**13. Available Square Feet**

* The amount of vacant usable spacve ready for occupancy

**14. Construction Date**

* The date the buildings construction was originally finished

**15. Congressional District**

* Represents the specific federal congressional district where the property is physically located

**16. Congressional District Representative Name**

* The name of the U.S Representative serving the district

**17. Bulding Status**

* Describes the operational state of the property

**18. Real Property Asset Type**

* Classifies whether the property is a building, land or a structure